api_url = "X"
inpatient_username = "X"
inpatient_password = "X"
ambulatory_password = "X"
inpatient_instance = "X"
inpatient_facility_id = "X"
ambulatory_instance = "X"
ambulatory_facility_id = "X"

log_file = "/logs/mdstaff_log.txt"
id_table = "/data/"
